### ISSUE TITLE
CustomTools limited?

### ISSUE THREAD

**Issue by matheeuslima** [zelythia/AutoTools#10]
Hi,
This is not an error but rather a question, does the CustomTools option have a limit? How does it work if I want to place several specific blocks? Because I play on a server where certain blocks can only be broken with a specific pickaxe, for example:

Stone only brakes with stone pickaxes

Deepslate only with iron pickaxe

and in the config in the customtools part it looks like this 

customTools={"minecraft:dirt":"minecraft:iron_shovel"}
customTools={"minecraft:gravel":"minecraft:iron_shovel"}
customTools={"minecraft:cobblestone":"minecraft:stone_pickaxe"}
customTools={"minecraft:granite":"minecraft:stone_pickaxe"}
customTools={"minecraft:deepslate":"minecraft:iron_pickaxe"}
customTools={"minecraft:andesite":"minecraft:stone_pickaxe"}
customTools={"minecraft:stone":"minecraft:stone_pickaxe"}

However, in the game, one always stops working and it starts working again if I delete one from the list and if I add another one the old one stops working.

**Comment by zelythia** [comment]
Hi, sorry for the late reply. The customTools config is treated as a Json object and there should only ever be one in the AutoTools config file. If you want to add multiple custom tool/block combinations it would look like this:
`customTools={"minecraft:dirt":"minecraft:iron_shovel", "minecraft:gravel":"minecraft:iron_shovel", "minecraft:cobblestone":"minecraft:stone_pickaxe", "minecraft:granite":"minecraft:stone_pickaxe", "minecraft:deepslate":"minecraft:iron_pickaxe", "minecraft:andesite":"minecraft:stone_pickaxe", "minecraft:stone":"minecraft:stone_pickaxe"}
`
