### ISSUE TITLE
when enabled on toggle mode, it uses axe for gravel

### ISSUE THREAD

**Issue by lavoicor** [zelythia/AutoTools#13]
while breaking gravel block, it insists on using the axe to break it. this is with every combination of settings aswell. only fix is to turn off toggle mode and use button mode (pressing/holding alt)

**Comment by lavoicor** [comment]
using fabric 0.15.11, on minecraft 1.20.6

**Comment by lavoicor** [comment]
?

**Comment by zelythia** [comment]
Hi, sorry for the late reply. I believe the problem was that AutoTools would still factor in efficiency even though the tool was incorrect. The problem should be resolved with in the next update for AutoTools.
