### ISSUE TITLE
Keybind to toggle AutoTools does not exist

### ISSUE THREAD

**Issue by kierkat10** [zelythia/AutoTools#15]
I have searched far and wide in my controls and the keybind to toggle the mod on and off just does not exist. I was able to find it in older versions of the game though.

**Comment by zelythia** [comment]
Hi, what version of Minecraft are you playing on and what modloader are you using?

**Comment by kierkat10** [comment]
i am playing on 1.21 and using modrinth fabric to load my mods. once i get home from school i will test to see if it is there if i disable all of my other mods

**Comment by kierkat10** [comment]
sorry for the really late response!
i disabled all other mods and i still only see this keybind.
![image](https://github.com/user-attachments/assets/b18769ab-fe31-4f2a-bdc7-cb0b1934b110)
this is a completely different keybind, and i have not been able to find the toggle one.

**Comment by zelythia** [comment]
AutoTools uses the same keybind for toggle and manual tool picking so this is the one you're looking for. But you're right, the naming can be confusing and I'll change it in the next update.
