### ISSUE TITLE
2.1 For 1.20.4

### ISSUE THREAD

**Issue by Spike-has-no-idea-how-to-code** [zelythia/AutoTools#17]
Please do not skip this version for 2.1, I cant use the mod because of the bugs that are only fixed in 2.1.

**Comment by Spike-has-no-idea-how-to-code** [comment]
Im hoping that this will be a simple change to the version requirements, and if so there is no reason not to do so.

**Comment by kierkat10** [comment]
you know you can just install it anyways

**Comment by Spike-has-no-idea-how-to-code** [comment]
actually you cant, it will force the game to crash because of the way its coded

**Comment by kierkat10** [comment]
uh huh ok, but i _also_ don't see anything wrong with getting 1.21 either so

**Comment by Spike-has-no-idea-how-to-code** [comment]
Why are you fighting me? You aren’t the dev, and I can’t just “get” 1.21 because I have other mods that have not updated. My request stands, I need this update for my version.

**Comment by kierkat10** [comment]
i'm not attempting to "fight" you, i'm just simply stating some alternative solutions for your problem.
i am not the developer either, yet i am still inclined to believe that he will not update the mod for an older minecraft version.

i am aware that my previous comments may have sounded a bit harsh, but i did have good intentions.

**Comment by zelythia** [comment]
AutoTools will only be updated for 1.20.1 and 1.20.6 as these are the major and latest versions, but in the future the required versions won't be enforced as harshly and the release for 1.20.1 should probably work with 1.20.4 (apart from shears because of the changed id of grass)

**Comment by Spike-has-no-idea-how-to-code** [comment]
Thanks, that’s all I needed really. As long as the version requirements are less strict, I can just use that
