### ISSUE TITLE
Bug with 2 pickaxes on server

### ISSUE THREAD

**Issue by FakeStu** [zelythia/AutoTools#4]
I have two pickaxes, one with Fortune, the other with Silk Touch (obviously both in inventory), using the newest version (v2) they get glitched and I literally can't mine the block I'm trying to, both pickaxes get switched in the inventory, they get put in the crafting of the inventory.

Doing the same thing when using last version (v1.9) this doesn't happen, but it just doesn't do anything, it is not following the config I want to, that would be "Prefer Silk Touch: Except ores", it just use the Fortune 3 pickaxe.

I tried both versions and this seems to only happen in multiplayer, for the server I've tried.

Any help would be appreciated, I love this mod.

These are my configs: 
#AutoTools config

#AutoTools will always be active and try to get you the best tool. Can be toggled with the set key.
toggle=true
#Disables AutoTools in creative-mode if toggle is enabled
disableCreative=true
#Keeps the selected slot when swapping to a new tool instead of using the vanilla mechanics.
keepSlot=true
#AutoTools will prefer the tool already in your hotbar if multiple tools have the same mining speed, regardless their durability
preferHotBarTool=false
#AutoTools will prefer the tool with the lower durability, instead of the higher one, if they have the same mining speed
preferLowDurability=false
#Autotools will try to always get a tool with Fortune for gravel and leaves
alwaysPreferFortune=false

#AutoTools only tries to get a new tool if it is needed to break the block
onlySwitchIfNecessary=false
#AutoTools will switch back to you previous tool or item you had in your hand before breaking the block
switchBack=true
#Displays the weapons Dps when hovering over it as an tooltip
showDPS=true
#AutoTools will change to the tool with the most DPS when looking at an entity
changeForEntities=false

#Autotools will prefer Silk Touch:
# never, always, always_ores, except_ores
preferSilkTouch=never

#Add custom block-tool-configurations in JSON format
#e.g. customTools={"minecraft:block_id":"minecraft:tool_id"} or customTools={"minecraft:block_id":["minecraft:tool_id_1", "minecraft:tool_id_2"]}
#When adding multiple tools, the first one has the highest priority
#There are also pre-define lists for tool groups: autotools:pickaxe, autotools:axe, autotools:shovel, autotools.hoe, autotools:sword
customTools={}

**Comment by zelythia** [comment]
The issue should hopefully be fixed in the next update which will be released sometime next week

**Comment by FakeStu** [comment]
I forgot to mention on the post I was playing on 1.20.1, the fix will be available for that version too?

**Comment by zelythia** [comment]
Yes, of course

**Comment by FakeStu** [comment]
I would like to ask you some other question about the mod cause I'm not sure if something are bugs or something else.
Is this thread ok for me to do so or can I contact you in any other way you prefer?

**Comment by zelythia** [comment]
This thread is ok. If it is another bug I'll create a new issue on Github

**Comment by FakeStu** [comment]
Ok so, the other few things I found that I remember are:
1) When the mod is active and switch me the tools, sometimes after using the tools the inventory is gonna be not sorted as it was before using the tools
2) If I had some free slots in the hotbar, sometimes the tool is gonna remain in those slots that were free
![Screenshot 2024-05-12 161806](https://github.com/zelythia/AutoTools/assets/84995343/49ad7440-fd29-4bb9-b178-9facf3b56b63)
![Screenshot 2024-05-12 161836](https://github.com/zelythia/AutoTools/assets/84995343/0bc933bb-a959-4cd4-b841-7d1a518a3816)

3) I don't know if this is considerable as a bug or if it could be as a setting, but when mining deepslate (in singleplayer, so without the original bug of this thread) the mod is gonna use silk touch pickaxe, even if it hasn't so much sense, being that only cobble deepslate has craftings

**Comment by zelythia** [comment]
1. and 2. should also be fixed in the next update. 
As for 3. : I would argue that Deepslate can also be seen as a building block and should be treated the same as Stone, so AutoTools just picks the Pickaxe with the highest mining speed or the first one it finds. Maybe I'll add an option in one of the next updates to blacklist certain blocks and add custom blocks for which AutoTools will preferr SilkTouch/Fortune

**Comment by FakeStu** [comment]
Thank you for your help and really quick answers, for the 3rd point, as it come easier for you honestly, even tho I would appreciate a setting for this type of things.

If, for the moment, a custom setting in the config is doable for a quick "fix", let me know.

**Comment by FakeStu** [comment]
Still a lot buggy, now sometimes it works having both pickaxe in the inventory, something it bugs itself, usually when it has to switch between the two pickaxe.

Now it's also buggy when having only 1 pickaxe tho.
