### ISSUE TITLE
Shears + Cobweb

### ISSUE THREAD

**Issue by Jhubbz** [zelythia/AutoTools#7]
Should this be selecting shears when trying to break cobweb, or did I do some setting wrong?

**Comment by zelythia** [comment]
Yes it should, please provide the version and modloader you are playing on and also your config if you have changed any values from the defualt ones so I can look into the issue. Also, are you using the latest version (v2.1) of AutoTools?

**Comment by Jhubbz** [comment]
Sorry, I'm pretty new to using mods so I'm not sure how to provide the 'config'. Do I open the autotools.properties in Word and paste it here? I guess I'll just drop in a screenshot of my settings menu and hope that helps?

![AutoToolsSettings](https://github.com/zelythia/AutoTools/assets/170060034/e5dcb42a-e7ed-475e-b84b-3d107602f4bf)


Also the server I'm on is 1.20.4 so that's what I'm using, if it needs to be the 1.20.6 version for this part to work, I'll just wait until we update!
I'm using the Feather client, and I got AutoTools through that, it says I have MC Version: 1.20.4 FB, Mod Version: Latest (2).
Thanks for responding!

**Comment by zelythia** [comment]
Sorry for the really late reply, but this issue should be fixed in the next release of AutoTools
