### ISSUE TITLE
Option to choose which hotbar slots use autotool

### ISSUE THREAD

**Issue by mulfok** [zelythia/AutoTools#8]
Tweakeroo has a similar "toolSwitch" tweak, but you can specify which slots let you do autotool, and which don't, by range or list of hotbar numbers.

e.g, I only want to use the first slot as my autotool slot, with similar behaviour to AutoTool's existing "keep selected slot"
![image](https://github.com/zelythia/AutoTools/assets/50339059/a6ae564c-6776-4dba-a2c1-58171627f5b7)

here's what it looks like in game:
![javaw_grKjd0T1ms](https://github.com/zelythia/AutoTools/assets/50339059/e6b0ce21-0b37-45ad-a406-2e6860e586da)

If I had set toolSwitchIgnoredSlots to 3-9, and tried to use the second slot to mine wood, it would swap to the first slot, and swap the tool to be put _into slot 1_ if necessary.

I hope that it explains the feature thoroughly enough, it'd be a great addition to the mod, and would replace tweakeroo for me entirely, since I really only use it for this one little feature. Thanks in advance for your consideration.

**Comment by ValokAsura** [comment]
I'm using Tweakeroo for 1.21 as well, just as a temporary replacement for my slightly buggy AutoTools. This would be a nice feature to have, and just like mulfok, this feature would allow me to get rid of Tweakeroo.

**Comment by mulfok** [comment]
Hiya, just writing to let you know that I've tried out the implemented feature in game, and it works beautifully. Thanks so much for implementing it!
